# Generated by Django 6.0.5 on 2026-05-28 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_book_id_alter_category_id_alter_review_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="totalrating",
        ),
        migrations.RemoveField(
            model_name="book",
            name="totalreview",
        ),
        migrations.DeleteModel(
            name="Review",
        ),
    ]
