# Generated by Django 6.0.5 on 2026-06-05 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_remove_book_totalrating_remove_book_totalreview_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"verbose_name": "کتاب", "verbose_name_plural": "کتاب\u200cها"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "verbose_name": "دسته\u200cبندی",
                "verbose_name_plural": "دسته\u200cبندی\u200cها",
            },
        ),
        migrations.AlterModelOptions(
            name="slider",
            options={"verbose_name": "اسلاید", "verbose_name_plural": "اسلایدها"},
        ),
        migrations.AlterModelOptions(
            name="writer",
            options={"verbose_name": "نویسنده", "verbose_name_plural": "نویسندگان"},
        ),
        migrations.AlterField(
            model_name="book",
            name="bookpage",
            field=models.FileField(upload_to="bookpage/", verbose_name="فایل کتاب"),
        ),
        migrations.AlterField(
            model_name="book",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="store.category",
                verbose_name="دسته\u200cبندی",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="coverpage",
            field=models.FileField(upload_to="coverpage/", verbose_name="تصویر جلد"),
        ),
        migrations.AlterField(
            model_name="book",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ثبت"),
        ),
        migrations.AlterField(
            model_name="book",
            name="description",
            field=models.TextField(verbose_name="توضیحات"),
        ),
        migrations.AlterField(
            model_name="book",
            name="name",
            field=models.CharField(max_length=100, verbose_name="نام کتاب"),
        ),
        migrations.AlterField(
            model_name="book",
            name="price",
            field=models.IntegerField(verbose_name="قیمت (تومان)"),
        ),
        migrations.AlterField(
            model_name="book",
            name="slug",
            field=models.SlugField(max_length=100, verbose_name="شناسه URL"),
        ),
        migrations.AlterField(
            model_name="book",
            name="status",
            field=models.IntegerField(
                choices=[(0, "فعال"), (1, "غیرفعال")], default=0, verbose_name="وضعیت"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="stock",
            field=models.IntegerField(verbose_name="موجودی"),
        ),
        migrations.AlterField(
            model_name="book",
            name="updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="آخرین به\u200cروزرسانی"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="writer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.writer",
                verbose_name="نویسنده",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="create_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
        ),
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.FileField(upload_to="category/", verbose_name="آیکون"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, verbose_name="نام"),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                max_length=150, unique=True, verbose_name="شناسه URL"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="updated_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="آخرین به\u200cروزرسانی"
            ),
        ),
        migrations.AlterField(
            model_name="slider",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
        ),
        migrations.AlterField(
            model_name="slider",
            name="slideimg",
            field=models.FileField(upload_to="slide/", verbose_name="تصویر اسلاید"),
        ),
        migrations.AlterField(
            model_name="slider",
            name="title",
            field=models.CharField(max_length=150, verbose_name="عنوان"),
        ),
        migrations.AlterField(
            model_name="slider",
            name="updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="آخرین به\u200cروزرسانی"
            ),
        ),
        migrations.AlterField(
            model_name="writer",
            name="bio",
            field=models.TextField(verbose_name="بیوگرافی"),
        ),
        migrations.AlterField(
            model_name="writer",
            name="create_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
        ),
        migrations.AlterField(
            model_name="writer",
            name="name",
            field=models.CharField(max_length=100, verbose_name="نام"),
        ),
        migrations.AlterField(
            model_name="writer",
            name="pic",
            field=models.FileField(upload_to="writer/", verbose_name="تصویر"),
        ),
        migrations.AlterField(
            model_name="writer",
            name="slug",
            field=models.SlugField(
                max_length=150, unique=True, verbose_name="شناسه URL"
            ),
        ),
        migrations.AlterField(
            model_name="writer",
            name="updated_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="آخرین به\u200cروزرسانی"
            ),
        ),
    ]
