# Generated by Django 6.0.5 on 2026-06-06 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_alter_book_options_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="status",
            field=models.IntegerField(default=0, verbose_name="وضعیت"),
        ),
    ]
