# Generated by Django 6.0.5 on 2026-06-05 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_alter_order_id_alter_orderitem_id"),
        ("store", "0005_alter_book_options_alter_category_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ("-created",),
                "verbose_name": "سفارش",
                "verbose_name_plural": "سفارش\u200cها",
            },
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "verbose_name": "آیتم سفارش",
                "verbose_name_plural": "آیتم\u200cهای سفارش",
            },
        ),
        migrations.AlterField(
            model_name="order",
            name="account_no",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="شماره حساب"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="آدرس"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ثبت"),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="مشتری",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="district",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="شهر"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="division",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="استان"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="ایمیل"),
        ),
        migrations.AlterField(
            model_name="order",
            name="name",
            field=models.CharField(max_length=30, verbose_name="نام گیرنده"),
        ),
        migrations.AlterField(
            model_name="order",
            name="paid",
            field=models.BooleanField(default=False, verbose_name="پرداخت شده"),
        ),
        migrations.AlterField(
            model_name="order",
            name="payable",
            field=models.IntegerField(verbose_name="مبلغ قابل پرداخت (تومان)"),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="روش پرداخت"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.CharField(max_length=16, verbose_name="شماره تماس"),
        ),
        migrations.AlterField(
            model_name="order",
            name="totalbook",
            field=models.IntegerField(verbose_name="تعداد کتاب"),
        ),
        migrations.AlterField(
            model_name="order",
            name="transaction_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="کد تراکنش"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="آخرین به\u200cروزرسانی"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="zip_code",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="کد پستی"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="store.book",
                verbose_name="کتاب",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="order.order",
                verbose_name="سفارش",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="قیمت"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="تعداد"),
        ),
    ]
