# Generated by Django 6.0.5 on 2026-06-06 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_alter_order_options_alter_orderitem_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payable",
            field=models.IntegerField(verbose_name="مبلغ قابل پرداخت"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="order.order",
                verbose_name="سفارش",
            ),
        ),
    ]
